IMG_CVPATH = "https://seungdata.princeton.edu/pinky100-em/aligned/v0"
SEG_CVPATH = "https://seungdata.princeton.edu/pinky100-ws/agg_pinky100/v185"
CLF_CVPATH = "https://seungdata.princeton.edu/pinky100-clefts/mip1_d2_1175k"
MITO_CVPATH = "https://seungdata.princeton.edu/pinky100-mito/seg_191220"
NUC_CVPATH = "https://seungdata.princeton.edu/pinky100-nuclei/seg"

IMG_SOURCE = f"precomputed://{IMG_CVPATH}"
SEG_SOURCE = f"precomputed://{SEG_CVPATH}"
MITO_SOURCE = f"precomputed://{MITO_CVPATH}"
NUC_SOURCE = f"precomputed://{NUC_CVPATH}"
CLF_CVPATH = f"precomputed://{CLF_CVPATH}"
